fix: don't raise an exception when ActiveJob isn't loaded (#523)
* Avoid raising an error when ActiveJob isn't loaded

If ActiveJob isn't loaded (by not requiring active_job/railtie in config/application.rb),
then this error occur when Honeybadger is loaded:

plugin error name=active_job class=NoMethodError message="undefined method `active_job' for an instance of Rails::Application::Configuration"

This change rescues that error and disables the plugin.

* Update active_job.rb

Check for method with `respond_to?` instead of raising exception

---------

Co-authored-by: Joshua Wood <josh@joshuawood.net>