Lock delayed_job version to fix test error.
See https://github.com/collectiveidea/delayed_job/pull/931

This is the error this fixes:

  ~/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/deprecation/proxy_wrappers.rb:124:in `initialize': undefined method `instance' for ActiveSupport::Deprecation:Class (NoMethodError)
  Did you mean?  instance_of?
    from ~/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/deprecation/proxy_wrappers.rb:10:in `new'
    from ~/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/deprecation/proxy_wrappers.rb:10:in `new'
    from ~/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/core_ext/load_error.rb:30:in `<top (required)>'
    from ~/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:12:in `require'
    from ~/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:12:in `<top (required)>'
    from ~/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/delayed_job-4.1.2/lib/delayed/worker.rb:2:in `require'

After delayed_job fixes the bug we can unlock the dependency.
delayed_job tests must then be locked (on Travis) to Ruby >= 2.2.2 to
support ActiveSupport >= 5.0.