Warn when notification server can't be found by cap3.
Previously this caused the exception:

  NoMethodError: undefined method `select?' for nil:NilClass

See #99.